name: simtech
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.1.3
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  flutter_svg: ^1.0.0
  freezed_annotation: ^1.0.0
  google_fonts: ^2.1.0
  json_annotation: ^4.4.0
  layout: ^1.0.2
  responsive_builder: ^0.4.1
  smooth_page_indicator: ^1.0.0+2
  universal_html: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2+1
  json_serializable: ^6.1.1

dependency_overrides:
  flutter_svg: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Barlow
      fonts:
        # - asset: assets/fonts/Barlow-Black.ttf
        #   weight: 800
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow/Barlow-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
          weight: 100
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis/Dosis-Light.ttf
          weight: 300
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.ttf
          weight: 200