name: simtech
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  charts_flutter: ^0.12.0
  circular_widgets: ^2.1.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  directed_graph: ^0.3.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  layout: ^1.0.3
  linkify: ^4.1.0
  percent_indicator: ^4.2.2
  smooth_page_indicator: ^1.0.0+2
  tuple: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.6
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/fzyzcjy/charts/
      ref: master
      path: charts_flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
  fonts:
    - family: PackagesIcons
      fonts:
        - asset: assets/fonts/PackagesIcons.ttf
    - family: MachinesIcons
      fonts:
        - asset: assets/fonts/MachinesIcons.ttf
    - family: Barlow
      fonts:
        # - asset: assets/fonts/Barlow-Black.ttf
        #   weight: 800
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow/Barlow-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
          weight: 100
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis/Dosis-Light.ttf
          weight: 300
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.ttf
          weight: 200