name: simrecicla
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  charts_flutter: ^0.12.0
  circular_widgets: ^3.0.0
  collection: ^1.16.0
  directed_graph: ^0.3.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  go_router: ^5.2.4
  hooks_riverpod: ^2.1.1
  intl: ^0.17.0
  layout: ^1.0.3
  linkify: ^4.1.0
  percent_indicator: ^4.2.2
  smooth_page_indicator: ^1.0.0+2
  tuple: ^2.0.1
  universal_html: ^2.0.8
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen: ^5.1.0+1
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  freezed: ^2.3.2

flutter_gen:
  integrations:
    flutter_svg: true
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: PackagesIcons
      fonts:
        - asset: assets/fonts/PackagesIcons.ttf
    - family: MachinesIcons
      fonts:
        - asset: assets/fonts/MachinesIcons.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600